name: Dependabot

on:
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  changeset:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: hmarr/debug-action@v3.0.0
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Upsert changeset
        uses: quantizor/dependabot-changesets@changelog
        with:
          owner: ${{ github.repository_owner }}
          repo: markdown-to-jsx
          pr-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          include-changelog: true
